### ISSUE TITLE
net5 - System.MissingMethodException

### ISSUE THREAD

**Issue by segfault-** [WahidBitar/EF-Core-Simple-Graph-Update#1]
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.INavigation Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.get_Metadata()'.
         at Diwink.Extensions.EntityFrameworkCore.DbContextExtensions.insertUpdateOrDeleteGraph[T](DbContext context, T newEntity, T existingEntity, String aggregateType)
         at Diwink.Extensions.EntityFrameworkCore.DbContextExtensions.InsertUpdateOrDeleteGraph[T](DbContext context, T newEntity, T existingEntity)

**Comment by WahidBitar** [comment]
Thank you
I've realized that it will not work on EF core 5.
I'll try to arrange a time to upgrade it to EF core 5.

Thanks

**Comment by TLA020** [comment]
Same issue here, anything planned for EF core 5?

**Comment by Moga-Andrei** [comment]
You can replace navigationEntry.Metadata.IsCollection() at line 59 with navigationEntry.Metadata.IsCollection and it will work on EF core(5.0.8 in my case)

**Comment by WahidBitar** [comment]
I've updated the nuget package to just support the 3.1.* EF core version.
I'll do my best to do another one that supports the newer EF core versions.
